/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_manuelvalladares;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author mevl1
 */
public class PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EMPLEADO = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        tf_usuario = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        cb_puesto = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        tf_contraseña = new javax.swing.JPasswordField();
        LOGIN = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        tf_pass = new javax.swing.JPasswordField();
        DULCERIA = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        tf_dc_nombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_dc_sabor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cb_dc_categorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_dulces = new javax.swing.JTree();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        menu = new javax.swing.JPopupMenu();
        pop_eliminar = new javax.swing.JMenuItem();
        pop_modificar = new javax.swing.JMenuItem();
        PELICULAS = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_pel_nombre = new javax.swing.JTextField();
        tf_pel_duracion = new javax.swing.JTextField();
        tf_pel_clas = new javax.swing.JTextField();
        cb_peliculas = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_peliculas = new javax.swing.JTree();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        pop_pelis = new javax.swing.JPopupMenu();
        pop_pelis_eliminar = new javax.swing.JMenuItem();
        pop_pelis_modificar = new javax.swing.JMenuItem();
        ASEO = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_as_nombre = new javax.swing.JTextField();
        tf_as_descripcion = new javax.swing.JTextField();
        cb_aseo = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_aseo = new javax.swing.JTree();
        pop_aseo = new javax.swing.JPopupMenu();
        eliminar = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        ADMINISTRADOR = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_admin_user = new javax.swing.JTextField();
        tf_admin_contra = new javax.swing.JPasswordField();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("FECHA DE NACIMIENTO");

        jLabel3.setText("USUARIO");

        jLabel4.setText("CONTRASEÑA");

        jLabel5.setText("CORREO");

        jLabel6.setText("PUESTO");

        cb_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dulceria", "Boleteria", "Aseo" }));

        jButton2.setText("Guardar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EMPLEADOLayout = new javax.swing.GroupLayout(EMPLEADO.getContentPane());
        EMPLEADO.getContentPane().setLayout(EMPLEADOLayout);
        EMPLEADOLayout.setHorizontalGroup(
            EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EMPLEADOLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(72, 72, 72)
                .addGroup(EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_usuario)
                    .addComponent(tf_correo)
                    .addComponent(cb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        EMPLEADOLayout.setVerticalGroup(
            EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EMPLEADOLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EMPLEADOLayout.createSequentialGroup()
                        .addGroup(EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(EMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButton2)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jLabel7.setText("Usuario");

        jLabel8.setText("CONTRASEÑA");

        jButton4.setText("INICIAR");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LOGINLayout = new javax.swing.GroupLayout(LOGIN.getContentPane());
        LOGIN.getContentPane().setLayout(LOGINLayout);
        LOGINLayout.setHorizontalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LOGINLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(78, 78, 78)
                        .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_user, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(tf_pass)))
                    .addGroup(LOGINLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jButton4)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        LOGINLayout.setVerticalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton4)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jLabel9.setText("nombre");

        jLabel10.setText("sabor");

        jLabel11.setText("categoria");

        cb_dc_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolates", "Gomitas", "Paletas", "Chicle" }));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("dulces");
        jt_dulces.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_dulces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_dulcesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_dulces);

        jButton5.setText("agregar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("cerrar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DULCERIALayout = new javax.swing.GroupLayout(DULCERIA.getContentPane());
        DULCERIA.getContentPane().setLayout(DULCERIALayout);
        DULCERIALayout.setHorizontalGroup(
            DULCERIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DULCERIALayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(DULCERIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(111, 111, 111)
                .addGroup(DULCERIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DULCERIALayout.createSequentialGroup()
                        .addGroup(DULCERIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_dc_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_dc_nombre)
                            .addComponent(tf_dc_sabor, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DULCERIALayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(110, 110, 110))))
        );
        DULCERIALayout.setVerticalGroup(
            DULCERIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DULCERIALayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(DULCERIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_dc_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(DULCERIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(tf_dc_sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(DULCERIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_dc_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGroup(DULCERIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DULCERIALayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DULCERIALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(107, 107, 107))))
        );

        pop_eliminar.setText("eliminar");
        pop_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_eliminarActionPerformed(evt);
            }
        });
        menu.add(pop_eliminar);

        pop_modificar.setText("modificar");
        pop_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_modificarActionPerformed(evt);
            }
        });
        menu.add(pop_modificar);

        jLabel12.setText("Nombre");

        jLabel13.setText("duracion");

        jLabel14.setText("clasificacion");

        jLabel16.setText("categoria");

        cb_peliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terror", "Comedia", "Romance", "Drama", "Accion", "Infantil" }));

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Peliculas");
        jt_peliculas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_peliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_peliculasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_peliculas);

        jButton7.setText("agregar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("SALIR");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PELICULASLayout = new javax.swing.GroupLayout(PELICULAS.getContentPane());
        PELICULAS.getContentPane().setLayout(PELICULASLayout);
        PELICULASLayout.setHorizontalGroup(
            PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PELICULASLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 189, Short.MAX_VALUE))
            .addGroup(PELICULASLayout.createSequentialGroup()
                .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PELICULASLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PELICULASLayout.createSequentialGroup()
                                .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addGap(45, 45, 45)
                                .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_pel_clas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PELICULASLayout.createSequentialGroup()
                                        .addComponent(cb_peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(jButton7))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PELICULASLayout.createSequentialGroup()
                                .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(60, 60, 60)
                                .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_pel_duracion, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(tf_pel_nombre)))))
                    .addGroup(PELICULASLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PELICULASLayout.setVerticalGroup(
            PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PELICULASLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_pel_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_pel_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_pel_clas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PELICULASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cb_peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(47, 47, 47))
        );

        pop_pelis_eliminar.setText("eliminar");
        pop_pelis_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_pelis_eliminarActionPerformed(evt);
            }
        });
        pop_pelis.add(pop_pelis_eliminar);

        pop_pelis_modificar.setText("jMenuItem2");
        pop_pelis_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_pelis_modificarActionPerformed(evt);
            }
        });
        pop_pelis.add(pop_pelis_modificar);

        jLabel15.setText("NOMBRE");

        jLabel17.setText("Descripcion");

        jLabel18.setText("FUNCION");

        cb_aseo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vidrios", "pisos", "mesas" }));

        jButton9.setText("agregar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("FUNCION");
        jt_aseo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_aseo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_aseoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_aseo);

        javax.swing.GroupLayout ASEOLayout = new javax.swing.GroupLayout(ASEO.getContentPane());
        ASEO.getContentPane().setLayout(ASEOLayout);
        ASEOLayout.setHorizontalGroup(
            ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ASEOLayout.createSequentialGroup()
                .addGroup(ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ASEOLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(ASEOLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(65, 65, 65)
                                .addComponent(tf_as_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ASEOLayout.createSequentialGroup()
                                .addGroup(ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(53, 53, 53)
                                .addGroup(ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_as_descripcion)
                                        .addComponent(cb_aseo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(ASEOLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton9)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        ASEOLayout.setVerticalGroup(
            ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ASEOLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ASEOLayout.createSequentialGroup()
                        .addGroup(ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_as_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel17))
                    .addComponent(tf_as_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(ASEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cb_aseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        eliminar.setText("eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        pop_aseo.add(eliminar);

        modificar.setText("modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        pop_aseo.add(modificar);

        jLabel19.setText("USUARIO");

        jLabel20.setText("CONTRASEÑA");

        jButton11.setText("INICIAR");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ADMINISTRADORLayout = new javax.swing.GroupLayout(ADMINISTRADOR.getContentPane());
        ADMINISTRADOR.getContentPane().setLayout(ADMINISTRADORLayout);
        ADMINISTRADORLayout.setHorizontalGroup(
            ADMINISTRADORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADMINISTRADORLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(ADMINISTRADORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(46, 46, 46)
                .addGroup(ADMINISTRADORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11)
                    .addGroup(ADMINISTRADORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_admin_user)
                        .addComponent(tf_admin_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        ADMINISTRADORLayout.setVerticalGroup(
            ADMINISTRADORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADMINISTRADORLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(ADMINISTRADORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_admin_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(ADMINISTRADORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_admin_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButton11)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("CREAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setText("LOG IN");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton10.setText("ADMIN");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1)
                        .addGap(74, 74, 74)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton10)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton10)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (bandera == 1) {
            EMPLEADO.setModal(true);
            EMPLEADO.pack();
            EMPLEADO.setLocationRelativeTo(this);
            EMPLEADO.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Admin no detectado");

        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String nombre, usuario, contraseña, correo, puesto;
        Date fecha;
        nombre = tf_nombre.getText();
        usuario = tf_usuario.getText();
        contraseña = tf_contraseña.getText();
        correo = tf_correo.getText();
        puesto = (String) cb_puesto.getSelectedItem();
        fecha = fecha_nacimiento.getDate();
        EMPLEADO emp = new EMPLEADO(nombre, fecha, usuario, contraseña, correo, puesto);
        empleados.add(emp);
        //String nombre, Date nacimiento, String usuario, String contraseña, String correo, String puesto
        if (puesto.equals("Dulceria")) {
            dulceria.add(emp);
        }
        if (puesto.equals("Boleteria")) {
            boleteria.add(emp);
        }
        if (puesto.equals("Aseo")) {
            aseo.add(emp);
        }
        tf_contraseña.setText("");
        tf_correo.setText("");
        tf_nombre.setText("");
        tf_usuario.setText("");
        EMPLEADO.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if (bandera == 1) {
            LOGIN.setModal(true);
            LOGIN.pack();
            LOGIN.setLocationRelativeTo(this);
            LOGIN.setVisible(true);

        }

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String usuario;
        String email = tf_user.getText();
        String passw = tf_pass.getText();
        String puesto = "";
        int a = 0;
        int aux = 0;
        for (EMPLEADO u : empleados) {
            if (email.equals(u.getUsuario()) && passw.equals(u.getContraseña())) {
                if (u.getPuesto().equals("Dulceria")) {
                    a = 1;
                }
                if (u.getPuesto().equals("Boleteria")) {
                    a = 2;
                }
                if (u.getPuesto().equals("Aseo")) {
                    a = 3;
                }
                this.LOGIN.dispose();
                aux = 1;
            }

        }
        if (aux == 0) {
            JOptionPane.showMessageDialog(null, "el usuario o la contraseña es incorrecta");
        }
        if (a == 1) {
            DULCERIA.setModal(true);
            DULCERIA.pack();
            DULCERIA.setLocationRelativeTo(this);
            DULCERIA.setVisible(true);
        } else if (a == 2) {
            PELICULAS.setModal(true);
            PELICULAS.pack();
            PELICULAS.setLocationRelativeTo(this);
            PELICULAS.setVisible(true);

        } else if (a == 3) {
            ASEO.setModal(true);
            ASEO.pack();
            ASEO.setLocationRelativeTo(this);
            ASEO.setVisible(true);
        }


    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String nombre, sabor, categoria;
        nombre = tf_dc_nombre.getText();
        sabor = tf_dc_sabor.getText();
        categoria = (String) cb_dc_categorias.getSelectedItem();
        DefaultTreeModel m = (DefaultTreeModel) jt_dulces.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_dulces;
        int centinela = -1;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(categoria)) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new DULCERIA(nombre, sabor, categoria));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                centinela = 1;
            }
        }
        if (centinela == -1) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(categoria);
            DefaultMutableTreeNode p = new DefaultMutableTreeNode(new DULCERIA(nombre, sabor, categoria));
            n.add(p);
            raiz.add(n);
        }

        m.reload();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jt_dulcesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_dulcesMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar nodo con click derecho
            int row = jt_dulces.getClosestRowForLocation(evt.getX(), evt.getY());
            Object v1 = jt_dulces.getSelectionPath().getLastPathComponent();
            nodus = (DefaultMutableTreeNode) v1;
            if (nodus.getUserObject() instanceof DULCERIA) {
                duls = (DULCERIA) nodus.getUserObject();
                menu.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }


    }//GEN-LAST:event_jt_dulcesMouseClicked

    private void pop_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_eliminarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar?", "confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m = (DefaultTreeModel) jt_dulces.getModel();
            m.removeNodeFromParent(nodus);
            m.reload();
        }


    }//GEN-LAST:event_pop_eliminarActionPerformed

    private void pop_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_modificarActionPerformed
        // TODO add your handling code here:

        DefaultTreeModel s = (DefaultTreeModel) jt_dulces.getModel();
        duls.setNombre(JOptionPane.showInputDialog("nombre"));
        duls.setSabor(JOptionPane.showInputDialog("Sabor"));
        s.reload();

    }//GEN-LAST:event_pop_modificarActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        DULCERIA.setVisible(false);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        String nombre, duracion, clasificacion, categoria;
        nombre = tf_pel_nombre.getText();
        duracion = tf_pel_duracion.getText();
        clasificacion = tf_pel_clas.getText();
        categoria = (String) cb_peliculas.getSelectedItem();
        DefaultTreeModel m = (DefaultTreeModel) jt_peliculas.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_peliculas;
        int centinela = -1;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(categoria)) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new PELICULAS(nombre, duracion, clasificacion, categoria));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                centinela = 1;
            }
        }
        if (centinela == -1) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(categoria);
            DefaultMutableTreeNode p = new DefaultMutableTreeNode(new PELICULAS(nombre, duracion, clasificacion, categoria));
            n.add(p);
            raiz.add(n);
        }

        m.reload();


    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        PELICULAS.setVisible(false);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jt_peliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_peliculasMouseClicked
        // TODO add your handling code here:

        if (evt.isMetaDown()) {
            //seleccionar nodo con click derecho
            int row = jt_peliculas.getClosestRowForLocation(evt.getX(), evt.getY());
            Object v1 = jt_peliculas.getSelectionPath().getLastPathComponent();
            nodus1 = (DefaultMutableTreeNode) v1;
            if (nodus1.getUserObject() instanceof PELICULAS) {
                pels = (PELICULAS) nodus1.getUserObject();
                pop_pelis.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }

    }//GEN-LAST:event_jt_peliculasMouseClicked

    private void pop_pelis_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_pelis_eliminarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar?", "confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m = (DefaultTreeModel) jt_peliculas.getModel();
            m.removeNodeFromParent(nodus1);
            m.reload();
        }


    }//GEN-LAST:event_pop_pelis_eliminarActionPerformed

    private void pop_pelis_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_pelis_modificarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel s = (DefaultTreeModel) jt_peliculas.getModel();
        pels.setNombre(JOptionPane.showInputDialog("nombre"));
        pels.setCategoria(JOptionPane.showInputDialog("Categorias"));
        pels.setClasificacion(JOptionPane.showInputDialog("Clasificacion"));
        pels.setDuracion(JOptionPane.showInputDialog("duracion"));
        s.reload();


    }//GEN-LAST:event_pop_pelis_modificarActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        String nombre, descripcion, funcion;
        nombre = tf_as_nombre.getText();
        descripcion = tf_as_descripcion.getText();
        funcion = (String) cb_aseo.getSelectedItem();
        DefaultTreeModel m = (DefaultTreeModel) jt_aseo.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_aseo;
        int centinela = -1;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(funcion)) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new ASEO(nombre, descripcion, funcion));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                centinela = 1;
            }
        }
        if (centinela == -1) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(funcion);
            DefaultMutableTreeNode p = new DefaultMutableTreeNode(new ASEO(nombre, descripcion, funcion));
            n.add(p);
            raiz.add(n);
        }

        m.reload();
    }//GEN-LAST:event_jButton9MouseClicked

    private void jt_aseoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_aseoMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar nodo con click derecho
            int row = jt_aseo.getClosestRowForLocation(evt.getX(), evt.getY());
            Object v1 = jt_aseo.getSelectionPath().getLastPathComponent();
            nodus2 = (DefaultMutableTreeNode) v1;
            if (nodus2.getUserObject() instanceof ASEO) {
                as = (ASEO) nodus2.getUserObject();
                pop_aseo.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }


    }//GEN-LAST:event_jt_aseoMouseClicked

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar?", "confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m = (DefaultTreeModel) jt_aseo.getModel();
            m.removeNodeFromParent(nodus2);
            m.reload();
        }


    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel s = (DefaultTreeModel) jt_aseo.getModel();
        as.setNombre(JOptionPane.showInputDialog("nombre"));
        as.setDescripcion((JOptionPane.showInputDialog("Descripcion")));
        as.setFuncion((JOptionPane.showInputDialog("Funcion")));
        s.reload();

    }//GEN-LAST:event_modificarActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        ADMINISTRADOR.setModal(true);
        ADMINISTRADOR.pack();
        ADMINISTRADOR.setLocationRelativeTo(this);
        ADMINISTRADOR.setVisible(true);

    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        String contraseña;
        String user;
        contraseña = tf_admin_contra.getText();
        user = tf_admin_user.getText();
        if (contraseña.equals(contra) && user.equals(admin)) {
            JOptionPane.showMessageDialog(this, "Ingresado exitosamente");
            bandera = 1;
            ADMINISTRADOR.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "USUARIO INVALIDO");
        }


    }//GEN-LAST:event_jButton11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ADMINISTRADOR;
    private javax.swing.JDialog ASEO;
    private javax.swing.JDialog DULCERIA;
    private javax.swing.JDialog EMPLEADO;
    private javax.swing.JDialog LOGIN;
    private javax.swing.JDialog PELICULAS;
    private javax.swing.JComboBox<String> cb_aseo;
    private javax.swing.JComboBox<String> cb_dc_categorias;
    private javax.swing.JComboBox<String> cb_peliculas;
    private javax.swing.JComboBox<String> cb_puesto;
    private javax.swing.JMenuItem eliminar;
    private com.toedter.calendar.JDateChooser fecha_nacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jt_aseo;
    private javax.swing.JTree jt_dulces;
    private javax.swing.JTree jt_peliculas;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JPopupMenu pop_aseo;
    private javax.swing.JMenuItem pop_eliminar;
    private javax.swing.JMenuItem pop_modificar;
    private javax.swing.JPopupMenu pop_pelis;
    private javax.swing.JMenuItem pop_pelis_eliminar;
    private javax.swing.JMenuItem pop_pelis_modificar;
    private javax.swing.JPasswordField tf_admin_contra;
    private javax.swing.JTextField tf_admin_user;
    private javax.swing.JTextField tf_as_descripcion;
    private javax.swing.JTextField tf_as_nombre;
    private javax.swing.JPasswordField tf_contraseña;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_dc_nombre;
    private javax.swing.JTextField tf_dc_sabor;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JTextField tf_pel_clas;
    private javax.swing.JTextField tf_pel_duracion;
    private javax.swing.JTextField tf_pel_nombre;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
ArrayList<EMPLEADO> empleados = new ArrayList();
    ArrayList<EMPLEADO> dulceria = new ArrayList();
    ArrayList<EMPLEADO> boleteria = new ArrayList();
    ArrayList<EMPLEADO> aseo = new ArrayList();
    DefaultMutableTreeNode nodus;
    DefaultMutableTreeNode nodus1;
    DefaultMutableTreeNode nodus2;
    DULCERIA duls;
    PELICULAS pels;
    ASEO as;
    String admin = "admin";
    String contra = "1234";
    int bandera = 0;
}
